import type { NextPage } from 'next'
import Head from 'next/head'
import { useEffect, useRef, useState } from 'react'
import 'swiper/css'
import { Swiper, SwiperSlide } from 'swiper/react'
import CategoryNav from '../components/CategoryNav'
import ProductItem from '../components/ProductItem'
import { DUMMY_DATA, populateWithDummyData } from '../utils/general'
import useWindowDimensions from '../utils/hooks/useWindowDimensions'

const Home: NextPage = () => {
  const categories = useRef(['Back to school', 'New Arrivals', 'Coming soon'])
  const [selectedCategory, setSelectedCategory] = useState<
    'Back to school' | 'New Arrivals' | 'Coming soon'
  >('Back to school')

  const categoryItems = useRef(DUMMY_DATA)
  const [swiperInstance, setSwiperInstance] = useState<any>(null)

  const { width }: any = useWindowDimensions()

  const [slidersPerView, setSlidersPerView] = useState(1)

  useEffect(() => {
    const maxSlides = Math.floor(width / 380)
    setSlidersPerView(maxSlides)
  }, [width])

  const nextSlide = () => {
    swiperInstance.slideNext()
  }

  const prevSlide = () => {
    swiperInstance.slidePrev()
  }

  useEffect(() => {
    categoryItems.current = populateWithDummyData(30)
  }, [])

  return (
    <div className="home">
      <Head>
        <title>Tekki Demo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Tekki demo</h1>

      <CategoryNav
        categories={categories.current}
        setterFunction={setSelectedCategory}
        selectedCategory={selectedCategory}
        prevSlide={prevSlide}
        nextSlide={nextSlide}
      />
      <Swiper
        className="products"
        slidesPerView={slidersPerView}
        navigation
        spaceBetween={40}
        pagination={{ clickable: true }}
        onSwiper={(swiper) => setSwiperInstance(swiper)}
        onReachEnd={(e) => {
          if (swiperInstance) {
            swiperInstance.slideTo(0, 0)
          }
        }}
      >
        {categoryItems.current[selectedCategory].map((item, i) => {
          return (
            <SwiperSlide key={i}>
              <ProductItem
                key={i}
                productItem={item}
                productItemId={i}
              ></ProductItem>
            </SwiperSlide>
          )
        })}
      </Swiper>
    </div>
  )
}

export default Home
